version: '3.7'
services:
  server:
    container_name: shoe_project_server
    build:
      context: .
      dockerfile: $PWD/docker/Dockerfile.dev
    ports:
      - '8900:8900'
      - '42967:42967' # Hot Module Reloading for frontend
    environment:
      DATABASE_HOST: postgres
    volumes:
      - './:/app'

  postgres:
    container_name: shoe_project_postgres
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5432:5432'

  pgadmin:
    container_name: shoe_project_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@blueprint.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - 'pgadmin:/root/.pgadmin'
    ports:
      - '5050:80'

volumes:
  postgres:
  pgadmin:
