version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: $PWD/docker/Dockerfile.prod
    networks:
      - default
    ports:
      - 8900:8900
      # Hot Module Reloading for frontend
      - 42967:42967
    volumes:
      - "./:/app"
