version: "3.7"

services:
  seed:
    image: shoe_project_image
    container_name: shoe_project_seed
    command:
      - /bin/sh
      - -c
      - go run main.go seed
    volumes:
      - './:/app'
    env_file:
      - .env
    depends_on:
      - postgres

  backend:
    image: shoe_project_image
    container_name: shoe_project_backend
    ports:
      - "8900:8900"
    command:
      - /bin/sh
      - -c
      - CompileDaemon --command="./shoe-project server"
    volumes:
      - './:/app'
    env_file:
      - .env
    depends_on:
      - postgres
      - pgadmin

  frontend:
    image: shoe_project_image
    container_name: shoe_project_frontend
    ports:
      - "42967:42967" # Hot Module Reloading for frontend
      - "1234:1234"
    working_dir: "/app/ui"
    command:
      - /bin/sh
      - -c
      - |
        yarn watch &
        yarn start
    volumes:
      - "./:/app"
    env_file:
      - .env

  postgres:
    container_name: shoe_project_postgres
    image: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: shoe_project_pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - "pgadmin:/root/.pgadmin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
    logging:
      driver: none

volumes:
  postgres:
  pgadmin:
