version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: $PWD/docker/Dockerfile.dev
    container_name: shoe_project_server
    image: shoe_project_image
    ports:
      - '8900:8900'
      - '42967:42967' # Hot Module Reloading for frontend
    environment:
      DATABASE_HOST: postgres
    volumes:
      - './:/app'
    depends_on:
      - postgres

  migrations:
    container_name: shoe_project_migrations
    image: shoe_project_image
    environment:
      DATABASE_HOST: postgres
    command: "./shoe-project seed"
    depends_on:
      - postgres
      - server

  migrations:
    image: shoe_project_image
    environment:
      DATABASE_HOST: postgres
    command: "./shoe-project seed"
    depends_on:
      - postgres
      - server

  postgres:
    container_name: shoe_project_postgres
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5432:5432'

  pgadmin:
    container_name: shoe_project_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@blueprint.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - 'pgadmin:/root/.pgadmin'
    ports:
      - '5050:80'
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin:
