version: '3.7'

services:
  build-setup:
    image: shoe_project_image
    container_name: shoe_project_build_setup
    build:
      context: .
      dockerfile: './docker/Dockerfile.dev'
    environment:
      DATABASE_HOST: postgres
    command: './shoe-project seed'
    depends_on:
      - postgres

  server:
    image: shoe_project_image
    container_name: shoe_project_server
    environment:
      DATABASE_HOST: postgres
    ports:
      - '8900:8900'
    command:
      - /bin/sh
      - -c
      - |
          CompileDaemon --command="./shoe-project server"
    volumes:
      - './:/app'
    depends_on:
      - build-setup
      - postgres

  frontend:
    image: shoe_project_image
    container_name: shoe_project_frontend
    ports:
      - '42967:42967' # Hot Module Reloading for frontend
      - '1234:1234'
    working_dir: '/app/ui'
    command:
      - /bin/sh
      - -c
      - |
          yarn watch &
          yarn start
    volumes:
      - './:/app'

  postgres:
    container_name: shoe_project_postgres
    image: postgres
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5432:5432'

  pgadmin:
    container_name: shoe_project_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@blueprint.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    volumes:
       - 'pgadmin:/root/.pgadmin'
    ports:
      - '5050:80'
    depends_on:
      - postgres
    logging:
      driver: none

volumes:
  postgres:
  pgadmin:
