FROM golang:alpine

RUN apk add --update nodejs yarn git util-linux

WORKDIR /app
COPY . .

RUN go mod download
# Make sure we don't pollute the main docker-file
# CompileDaemon allows for hot reloading
RUN cd /tmp && go get github.com/githubnemo/CompileDaemon
RUN go build

EXPOSE 8900
# Want to run yarn watch in the background for hot reloading
CMD (cd ui && yarn watch &) && CompileDaemon --command="./shoe-project server"
