FROM golang:1.15

WORKDIR /app
COPY . /app

RUN go mod download
# Make sure we don't pollute the main docker-file
RUN cd /tmp && go get github.com/githubnemo/CompileDaemon && cd -
RUN go build -o shoe-project

EXPOSE 8900
CMD CompileDaemon --command="./shoe-project server"
