FROM golang:1.15

SHELL ["/bin/bash", "-c"]

# since we're starting non-interactive shell, 
# we wil need to tell bash to load .bashrc manually
ENV BASH_ENV ~/.bashrc
# needed by volta() function
ENV VOLTA_HOME /root/.volta
# make sure packages managed by volta will be in PATH
ENV PATH $VOLTA_HOME/bin:$PATH

# Using volta to manage node + yarn versions
RUN curl https://get.volta.sh | bash
RUN volta install node

WORKDIR /app
COPY . /app

RUN go mod download
# Make sure we don't pollute the main docker-file
# CompileDaemon allows for hot reloading
RUN cd /tmp && go get github.com/githubnemo/CompileDaemon
RUN go build

EXPOSE 8900
# Want to run yarn watch in the background for hot reloading
CMD (cd ui && yarn watch &) && CompileDaemon --command="./shoe-project server"
