FROM golang:1.15

WORKDIR /app
COPY . /app

RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon
RUN go build -o shoe-project

EXPOSE 8900
ENTRYPOINT CompileDaemon --command="./shoe-project server"
