name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      working-directory: ./ui
      run: yarn install
    - name: Build 
      working-directory: ./ui
      run: yarn run build-prod
    - name: Linting
      working-directory: ./ui
      run: |
        yarn lint:prettier
        yarn lint:prettier
        prettier --check src/
        eslint src/ --cache --format stylish
    - name: Testing
      working-directory: ./ui
      run: yarn test